bashtage/sphinx-material

- docs/customization.rst
- sphinx_material/__init__.py
- sphinx_material/sphinx_material/localtoc.html
- sphinx_material/sphinx_material/page.html
Fix root node naming to use pagename
> BUG: Fix root note naming

- docs/customization.rst
- sphinx_material/sphinx_material/globaltoc.html
- sphinx_material/sphinx_material/layout.html
- sphinx_material/sphinx_material/localtoc.html
- sphinx_material/sphinx_material/searchbox.html
- sphinx_material/sphinx_material/sidebar.html
> ENH: Remove errors in W3C

- README.rst
- docs/index.rst
> DOC: nav_name -> nav_title

- sphinx_material/sphinx_material/static/javascripts/version_dropdown.js
I think there's a small oversight with the dropdown-content div. I think you'll need to add some kind of class to color the background the selected theme color. '
Otherwise, when you scroll down, the background color won't update correctly.
> Need md-hero class on the dropdown-content element

- docs/conf.py
- sphinx_material/__init__.py
> ENH: Allow rebuilds when no changes

- sphinx_material/sphinx_material/layout.html
> BUG: Correct title

- docs/additional_samples.rst
- docs/basics.rst
- docs/conf.py
- docs/index.rst
- sphinx_material/sphinx_material/header.html
- sphinx_material/sphinx_material/layout.html
- sphinx_material/sphinx_material/logo-text.html
- sphinx_material/sphinx_material/relbar.html
- sphinx_material/sphinx_material/sidebar.html
- sphinx_material/sphinx_material/static/stylesheets/application.css
Correct escapes to be consistent with upstream
Revert #35 which causes issues
> BUG: Correct escapes and revert #35

- docs/additional_samples.rst
> DOC: Fix incorrect HTML

- sphinx_material/sphinx_material/static/stylesheets/application.css
Remove display block for pre>code
cloes #32
> BUG: Fix layout for production list

- .travis.yml
- MANIFEST.in
- docs/conf.py
- setup.py
Add requirements to manifest
Fix license
Add setup.cfg
> BUG: Ensure requirements is included

- docs/Makefile
- docs/conf.py
- docs/customization.rst
- docs/numpydoc.rst
- setup.py
- sphinx_material/__init__.py
- sphinx_material/sphinx_material/header.html
- sphinx_material/sphinx_material/layout.html
- sphinx_material/sphinx_material/theme.conf
- sphinx_material/sphinx_material/version_dropdown.html
> ENH: Improve versions dropdown

- docs/additional_samples.rst
- docs/conf.py
- docs/customization.rst
- sphinx_material/__init__.py
- sphinx_material/sphinx_material/theme.conf
- tools/sphinx-build-script.py
Allow users to white classes for tables
> ENH: User table classes

- docs/index.rst
- sphinx_material/__init__.py
- sphinx_material/sphinx_material/globaltoc.html
- sphinx_material/sphinx_material/static/stylesheets/application.css
Allow multiple captions
closes #48
> ENH: Allow multiple caption

- sphinx_material/__init__.py
- sphinx_material/sphinx_material/localtoc.html
> BUG: Fix localtoc

- requirements.txt
- sphinx_material/__init__.py
- sphinx_material/sphinx_material/globaltoc.html
- sphinx_material/sphinx_material/localtoc.html
- sphinx_material/sphinx_material/static/stylesheets/application-fixes.css
Use a single UL to avoid spacing issues
closes #50
> ENH: Merge multiple tocs into a single UL

- requirements.txt
Remove slugify dependency
closes #54
> BUG: Remove slugify

- README.rst
Closes https://github.com/bashtage/sphinx-material/issues/65#issuecomment-684807830
> Document the html_title function

- docs/additional_samples.rst
Add tables with alignment to help test #71
> DOC: Add tables with alignment

- README.rst
> DOC: Update readme

- docs/customization.rst
> DOC: Emphasize globaltoc
